//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusicCatalogue.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public Producer()
        {
            this.Albums = new HashSet<Album>();
        }
    
        public int ProducerID { get; set; }
        public string ProducerName { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
    }
}
